### PR TITLE
Presenting in ui thread

### PR DESCRIPTION
**Pull request by weihuoya**

### CODE REVIEW

**Comment by bunnei** [comment]
Thanks for the contribution! Just curious, can you expand a bit on what this improves/fixes so that we can test?

**Comment by weihuoya** [comment]
alternative way to present, hope it consume less battery.

**Comment by bunnei** [comment]
@weihuoya I noticed a bug with this. If you uninstall Citra, then reinstall, and then run any game that prompts for user permissions (such as microphone), presentation is broken. If you accept the prompt, presentation will work on subsequent game launches. Can you fix this? Thank you!

**Comment by bunnei** [comment]
@weihuoya thanks for updating! It looks like there is still a minor issue. The repro steps are similar - If you uninstall Citra, then reinstall, and then run any game that prompts for user permissions (such as microphone), presentation squishes the screen. Can you fix this? Thank you!

image

**Comment by weihuoya** [comment]
try to fix presentation squishes the screen after rotation, but it squishes when prompts for user permissions.
revert it.

**Comment by bunnei** [comment]
Seems to be working now. Thanks!

**Pull request merged**
