### PR TITLE
Dump unrelated builds from CI

### PR DESCRIPTION
**Pull request by AbandonedCart**
Considering this repository has been isolated from the Windows / MacOS builds, there should be no need to continue building them. This also covers changing the name of the repository for transifex to "citra-android"

I'm sure there is more required, since I have a feeling the current setup is probably for an Ubuntu build and not Android, either. This will at least eliminate the build failures that aren't a reflection of this repository.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
```
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
```

This is the basic, bare-bones setup for an Android build. It stops before the signing and upload phases because those are often replaced with third-party integrations (as recommended by GitHub). I personally use `r0adkll/sign-android-release@v1` and `marvinpinto/action-automatic-releases@v1.2.1` but they are definitely not the only options.

**Comment by SachinVin** [comment]
The plan was to eventually merge the android repository into upstream, but considering the lack of developers progress is slow. The ci was mostly left unchanged to make it easier to merge, and to allow the possibility to track any regressions that would make it difficult to merge it into upstream. The better fix would be to merge https://github.com/citra-emu/citra/pull/5623 and rebase.
We use bitrise for android builds, since the travis days, and it is good enough so we never switched.

**Comment by AbandonedCart** [comment]
I had a feeling the CI was left for that reason, hence completely isolating the removal as it's own pull and not submitting a replacement (to be reverted later). The Android build would best be a separate CI supplement to at least give an accurate status. 

I'm not sure if the issue referenced was the one intended, but it doesn't seem related. If a rebase is the better option, then don't let this PR stop it.

**Comment by SachinVin** [comment]
The issue is with the ci trying to build libyuv without installing the proper dependencies, simply surrounding it with an `if(ANDROID)` should stop the ci from failing, since libyuv is only really used on android.

**Comment by AbandonedCart** [comment]
Seems like a pretty easy fix then.

**Comment by SachinVin** [comment]
Yup, just that no one's really bothered to merge it.

**Comment by AbandonedCart** [comment]
Always glad to hear when a donation was money well spent. Oh well. Thanks for the info.

**Pull request closed without merging**
